--- 
- hosts: "{{ target | default('localhost') }}" 
  become: yes 
  roles: 
    - nodejs 
    - codedeploy
    - role: awslogs 
      vars:
        name: messages
        file: /var/log/messages
    - role: awslogs        
      vars:
        name: helloworld
        file: /var/log/helloworld/helloworld.log
        datetime_format: "%b %d %H:%M:%S"
